stages:
  - deploy

variables:
  projectName: Prepara.me - ADMIN
  projetctFolder: admin/admin.preparame.n1.homolog.inf.br
  shouldRunCompose: "false"
  projectPm2Name: admin.preparame.n1.homolog.inf.br
deploy_job:
  stage: deploy
  script:
    - echo "Deploying develop branch..."
    - echo "Acessando pasta do projeto..."
    - cd /var/www/$projetctFolder
    - git checkout .
    - git pull origin develop
    - echo "Dando permissão para a pasta do projeto..."
    - sudo chmod -R 777 /var/www/$projetctFolder
    - echo "Instalando dependências..."
    - npm install
    - echo "Gerando build..."
    - npx quasar build
    - echo "Publicando $projectName"
    - sudo pm2 restart $projectPm2Name
    - echo "Finalizando deploy..."
  tags:
    - homolog_sso
  only:
    - develop # Run on branches starting with ''
